nelmio_api_doc:
    documentation:
        info:
            title: Symfony API
            description: This is an api!
            version: 1.0.0
    models:
      names:
        - { alias: IndexController, type: App\Shared\Infrastructure\Symfony\Controller\IndexController }
    areas:
        path_patterns:
          - ^/api/v1(?!/doc$)
