version: '3.9'

services:
  app:
    container_name: symfony-app
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
      target: dev
      args:
        INSTALL_XDEBUG: ${DOCKER_INSTALL_XDEBUG:-false}
        INSTALL_COMPOSER_DEV: ${DOCKER_INSTALL_COMPOSER_DEV:-false}
    working_dir: /var/www
    environment:
      DOCKER: "1"
      PHP_IDE_CONFIG: "serverName=app.local"
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - ./.docker/php/php-fpm.conf:/etc/php/fpm/php-fpm.conf:ro
      - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
      - .:/var/www:delegated
    ports:
      - "${EXTERNAL_APP_PORT:-80}:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app

  db:
    container_name: kt-app-db
    image: postgres:16-alpine
    ports:
      - "${EXTERNAL_DB_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:

networks:
  app:
    driver: bridge
    name: app-network