parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    App\Shared\Infrastructure\Symfony\Listener\ExceptionListener:
        arguments:
            $environment: "%kernel.environment%"
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    App\Shared\Infrastructure\Symfony\Request\Resolver\JsonBodyResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: -50 }
