{{- if .Values.jobs.migrate.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "symfony-app.fullname" . }}-migrate-{{ now | date "20060102150405" }}
  labels:
    {{- include "symfony-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrate
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 2
  ttlSecondsAfterFinished: {{ .Values.jobs.migrate.ttlSecondsAfterFinished }}
  template:
    metadata:
      labels:
        {{- include "symfony-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migrate
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "symfony-app.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["php", "bin/console", "doctrine:migrations:migrate", "--no-interaction"]
          envFrom:
            - secretRef:
                name: {{ include "symfony-app.secretName" . }}
          resources:
            {{- toYaml .Values.jobs.migrate.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
