[php]
date.timezone = Europe/Warsaw
display_errors = Off
error_reporting = E_ALL & ~E_DEPRECATED
log_errors = 1
error_log = /proc/self/fd/2
catch_workers_output = yes
expose_php = Off
memory_limit = 500M
max_execution_time = 900
zend.exception_ignore_args = Off

upload_max_filesize = 15M
post_max_size = 16M

realpath_cache_size = 4096K
realpath_cache_ttl = 600

[opcache]
opcache.enable = 1
opcache.enable_cli = 1
opcache.memory_consumption = 192
opcache.max_accelerated_files = 20000
opcache.interned_strings_buffer = 16
opcache.save_comments = 1
opcache.validate_timestamps = 1
opcache.revalidate_freq = 0

[apcu]
apc.enabled = 1
apc.enable_cli = 1
apc.shm_size = 128M
apc.ttl = 0
apc.gc_ttl = 3600
