name: Check PR Title
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  check-pr-title:
    name: Check PR title
    runs-on: ubuntu-24.04

    steps:
      - uses: blumilksoftware/action-pr-title@v1.2.0
